# docker build -t albaz64/frp:0.61.0 -f Dockerfile.frp .
FROM golang:1.23 AS build

WORKDIR /build

RUN git clone https://github.com/fatedier/frp.git . &&\
    git checkout tags/v0.61.0

RUN make frps && make frpc

FROM scratch

COPY --from=build /build/bin/frps /usr/bin/frps
COPY --from=build /build/bin/frpc /usr/bin/frpc